remote_theme: nimiq/doc-theme
title: "Doc Theme"
description: "for GitHub Pages"
show_downloads: false
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
