title: "Nimiq"
description: "Theme for Documentations"
exclude: ["node_modules/*", "./*/*/**"]

submodule_section: "Demo Submodules"
submodules: "detailed"
ignore: ["sub3", "test"]

custom_header_tags: "custom-header-tags.html"
debugging: true
