theme: jekyll-theme-minimal
title: "Nimiq Documentation Theme"
description: "Doc template for GitHub pages."
show_downloads: false
markdown: kramdown
google_analytics:

baseurl: "/developer-reference"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
