remote_theme: nimiq/doc-theme
title: "Nimiq"
description: "Theme for Documentations"
exclude: ["node_modules/*", "./*/*/**"]

submodule_section: "Demo Submodules"
submodules: "detailed"

custom_header_tags: "custom-header-tags.html"
